# Generated by Django 5.0 on 2023-12-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
