# Generated by Django 5.0 on 2023-12-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_content_created_at_alter_content_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
