# Generated by Django 5.0 on 2023-12-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_content_created_at_alter_content_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='public',
            field=models.BooleanField(),
        ),
    ]
